// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2008-2023 Gaudenz Steinlin, Simon Harston, Jan Vorwerk,
//                         Per Magnusson (sireader2.py)
// Copyright (C) 2026 dulcilubio (JavaScript port)
// See NOTICE and LICENSE at the repository root.

/**
 * Run with: node --test test/
 *
 * The CRC vectors in crc-vectors.json were generated by running the original
 * Python implementation, so a passing run means this port computes exactly the
 * same checksums the Python library does.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { crc16, fromHex, hex, toBytes, toInt } from '../src/bytes.js';
import { buildCommand, FrameParser } from '../src/framer.js';
import {
  cardTypeFromDetect,
  cardTypeFromNumber,
  decodeBackupExtended,
  decodeCardData,
  decodeCardNumber,
  decodeStationCode,
  decodeTime,
} from '../src/protocol.js';
import { backupToCsv } from '../src/csv.js';
import { CMD, MODE } from '../src/constants.js';
import { SimulatedTransport } from '../src/simulator.js';
import { SIReadout } from '../src/readout.js';
import { SIControl } from '../src/control.js';
import { SIStation } from '../src/station.js';

const vectors = JSON.parse(
  readFileSync(new URL('./crc-vectors.json', import.meta.url), 'utf8')
);

test('CRC matches the Python implementation on every vector', () => {
  for (const [input, expected] of vectors) {
    assert.equal(hex(crc16(fromHex(input)), ''), expected, `input ${input}`);
  }
});

test('integers round-trip through toBytes and toInt', () => {
  for (const value of [0, 1, 255, 256, 65535, 1000000, 16777215]) {
    const width = value > 65535 ? 4 : 2;
    assert.equal(toInt(toBytes(value, width)), value);
  }
  assert.throws(() => toBytes(70000, 2), RangeError);
});

test('buildCommand frames a beep the way the manual describes', () => {
  const frame = buildCommand(CMD.BEEP, [0x01], false);
  // STX F9 01 01 CRC CRC ETX
  assert.equal(frame[0], 0x02);
  assert.equal(frame[1], 0xf9);
  assert.equal(frame[2], 0x01);
  assert.equal(frame[3], 0x01);
  assert.equal(frame.at(-1), 0x03);
  assert.deepEqual(Array.from(frame.subarray(4, 6)), Array.from(crc16(fromHex('f90101'))));

  const withWakeup = buildCommand(CMD.BEEP, [0x01], true);
  assert.equal(withWakeup[0], 0xff);
  assert.equal(withWakeup.length, frame.length + 1);
});

test('the parser reassembles a frame split across arbitrary chunks', () => {
  const frames = [];
  const parser = new FrameParser({ onFrame: (f) => frames.push(f) });
  // Build a valid station reply by hand: cmd F9, len 3, station 0x001F, data 01
  const inner = fromHex('f903001f01');
  const frame = new Uint8Array([0x02, ...inner, ...crc16(inner), 0x03]);

  for (const byte of frame) parser.push(Uint8Array.of(byte));
  assert.equal(frames.length, 1);
  assert.equal(frames[0].cmd, 0xf9);
  assert.equal(frames[0].station, 31);
  assert.deepEqual(Array.from(frames[0].data), [0x01]);

  // And in one go, twice over, with a wakeup byte in between.
  frames.length = 0;
  parser.push(new Uint8Array([...frame, 0xff, ...frame]));
  assert.equal(frames.length, 2);
});

test('the parser survives noise and a bad CRC', () => {
  const frames = [];
  const garbage = [];
  const naks = [];
  const parser = new FrameParser({
    onFrame: (f) => frames.push(f),
    onGarbage: (reason) => garbage.push(reason),
    onNak: () => naks.push(true),
  });

  const inner = fromHex('f903001f01');
  const good = new Uint8Array([0x02, ...inner, ...crc16(inner), 0x03]);
  const bad = new Uint8Array([0x02, ...inner, 0x00, 0x00, 0x03]);

  parser.push(new Uint8Array([0x15, 0x77, 0x88, ...bad, ...good]));

  assert.equal(naks.length, 1, 'the NAK is reported');
  assert.ok(garbage.length >= 1, 'the noise and bad frame are reported');
  assert.equal(frames.length, 1, 'the good frame still gets through');
});

test('card numbers decode for every series', () => {
  // SI-Card 5, series 0 and 1 are not printed on the card
  assert.equal(decodeCardNumber(Uint8Array.of(0, 0, 0x1e, 0x61)), 7777);
  assert.equal(decodeCardNumber(Uint8Array.of(0, 1, 0x1e, 0x61)), 7777);
  // SI-Card 5, series 2 prints as 2xxxxx
  assert.equal(decodeCardNumber(Uint8Array.of(0, 2, 0x1e, 0x61)), 207777);
  // SI-Card 9 stores the printed number directly
  assert.equal(decodeCardNumber(Uint8Array.of(0, 0x0f, 0x42, 0x40)), 1000000);
  assert.throws(() => decodeCardNumber(Uint8Array.of(1, 0, 0, 0)));

  assert.equal(cardTypeFromNumber(7777), 'SI5');
  assert.equal(cardTypeFromNumber(654321), 'SI6');
  assert.equal(cardTypeFromNumber(1234567), 'SI9');
  assert.equal(cardTypeFromNumber(2345678), 'SI8');
  assert.equal(cardTypeFromNumber(8100999), 'SI10');
  // The WM2003 batch of SI-Card 6 sits inside the SI-Card 8 number range
  assert.equal(cardTypeFromNumber(2003100), 'SI6');
  assert.equal(cardTypeFromNumber(42000000), null);

  // After an SI9_DET frame the family is already known, so that overlap
  // resolves the other way
  assert.equal(cardTypeFromDetect(2003100), 'SI8');
  assert.equal(cardTypeFromDetect(4100000), 'pCard');
  assert.equal(cardTypeFromDetect(654321), null);
});

test('station codes above 255 come out of the day byte', () => {
  assert.equal(decodeStationCode(31, null), 31);
  assert.equal(decodeStationCode(31, 0b01000000), 256 + 31);
  assert.equal(decodeStationCode(31, 0b11000000), 768 + 31);
});

test('times without a day byte pick the nearest earlier half day', () => {
  const reference = new Date(2026, 8, 10, 15, 0, 0); // Thu 15:00
  const morning = decodeTime(toBytes(10 * 3600, 2), null, reference);
  assert.equal(morning.getHours(), 10);
  assert.equal(morning.getDate(), 10);

  // 14:30 is stored as 2:30 in the afternoon half day
  const afternoon = decodeTime(toBytes(2 * 3600 + 1800, 2), null, reference);
  assert.equal(afternoon.getHours(), 14);
  assert.equal(afternoon.getMinutes(), 30);

  // 04:00 today is the most recent moment matching a raw value of 4 hours,
  // since 16:00 today has not happened yet
  const earlyToday = decodeTime(toBytes(4 * 3600, 2), null, reference);
  assert.equal(earlyToday.getDate(), 10);
  assert.equal(earlyToday.getHours(), 4);

  // Before noon, a raw value later than the current time must be yesterday
  // afternoon: 10 hours read at 08:00 means 22:00 last night
  const lastNight = decodeTime(toBytes(10 * 3600, 2), null, new Date(2026, 8, 10, 8, 0, 0));
  assert.equal(lastNight.getDate(), 9);
  assert.equal(lastNight.getHours(), 22);

  // 0xEEEE means nothing was recorded
  assert.equal(decodeTime(toBytes(0xeeee, 2), null, reference), null);
});

test('times with a day byte land on the right weekday', () => {
  const reference = new Date(2026, 8, 10, 15, 0, 0); // Thursday
  // Day byte for Tuesday morning: dow bits = 010, am
  const tuesday = decodeTime(toBytes(9 * 3600, 2), 0b0000_0100, reference);
  assert.equal(tuesday.getDay(), 2);
  assert.equal(tuesday.getDate(), 8);
  assert.equal(tuesday.getHours(), 9);

  // Same weekday as the reference but later in the day: a week ago
  const lastThursday = decodeTime(toBytes(5 * 3600, 2), 0b0000_1001, reference);
  assert.equal(lastThursday.getDate(), 3);
  assert.equal(lastThursday.getHours(), 17);
});

test('backup records decode, including error markers', () => {
  const record = new Uint8Array(8);
  record.set(toBytes(1234567, 3), 0);
  // 2026-09-10, afternoon
  record[3] = (26 << 2) | (9 >> 2);
  record[4] = ((9 & 0x3) << 6) | (10 << 1) | 1;
  record.set(toBytes(2 * 3600 + 15 * 60, 2), 5);
  record[7] = 128;

  const [punch] = decodeBackupExtended(record);
  assert.equal(punch.cardNumber, 1234567);
  assert.equal(punch.error, '');
  assert.equal(punch.time.getFullYear(), 2026);
  assert.equal(punch.time.getMonth(), 8);
  assert.equal(punch.time.getDate(), 10);
  assert.equal(punch.time.getHours(), 14);
  assert.equal(punch.time.getMinutes(), 15);
  assert.equal(punch.time.getMilliseconds(), 500);

  const broken = record.slice();
  broken[5] = 0xfa;
  assert.equal(decodeBackupExtended(broken)[0].error, 'ErrA');
});

test('the CSV matches the Config+ column layout', () => {
  const punches = [
    { time: new Date(2026, 8, 10, 14, 15, 0, 500), cardNumber: 1234567, error: '' },
    { time: new Date(2026, 8, 10, 0, 0, 0), cardNumber: 42, error: 'ErrA' },
  ];
  const csv = backupToCsv(punches, {
    code: 31,
    mode: 'Control',
    readTime: new Date(2026, 8, 10, 18, 0, 0),
  });
  const lines = csv.trim().split('\r\n');

  assert.equal(lines[0].split(';')[0], 'No');
  assert.equal(lines[0].split(';').length, 18);

  const row = lines[1].split(';');
  assert.equal(row[0], '1');
  assert.equal(row[2], '1234567');
  assert.equal(row[3], '2026-09-10   14:15:00.500');
  assert.equal(row[6], '31');
  assert.equal(row[7], 'Th');
  assert.equal(row[8], '14:15:00.500');
  assert.equal(row[9], 'Control');

  const errorRow = lines[2].split(';');
  assert.equal(errorRow[3], '2026-09-10   ErrA');
  assert.equal(errorRow[7], '');
  assert.equal(errorRow[8], '00:00:00');
});

test('end to end: a card is detected, read and decoded', async () => {
  const sim = new SimulatedTransport({ code: 31, mode: MODE.READOUT, latency: 0 });
  const station = new SIReadout(sim, { retries: 0, timeout: 1000 });
  await station.connect({ handshake: true });

  assert.equal(station.protoConfig.mode, MODE.READOUT);
  assert.equal(station.protoConfig.extendedProtocol, true);

  const info = await station.readInfo();
  assert.equal(info.code, 31);
  assert.equal(info.firmware, '656');
  assert.equal(info.modelName, 'BSM8-USB/SRR');
  assert.ok(Math.abs(info.voltage - 3.42) < 0.01);

  const base = new Date();
  base.setHours(10, 0, 0, 0);
  const expected = [31, 32, 45].map((code, i) => ({
    code,
    time: new Date(base.getTime() + (i + 1) * 60000),
  }));

  const card = await new Promise((resolve, reject) => {
    station.addEventListener('card', (e) => resolve(e.detail));
    station.addEventListener('cardError', (e) => reject(e.detail.error));
    sim.insertCard(8100999, { punches: expected });
  });

  assert.equal(card.cardNumber, 8100999);
  assert.equal(card.cardType, 'SI10');
  assert.equal(card.punches.length, 3);
  assert.deepEqual(card.punches.map((p) => p.code), [31, 32, 45]);
  assert.equal(card.punches[0].time.getHours(), 10);
  assert.equal(card.punches[0].time.getMinutes(), 1);

  await station.disconnect();
});

test('end to end: backup memory is read and turned into CSV', async () => {
  const sim = new SimulatedTransport({ code: 45, mode: MODE.CONTROL, latency: 0 });
  const now = new Date(2026, 8, 10, 12, 0, 0);
  sim.fillBackup([
    { cardNumber: 1234567, time: new Date(2026, 8, 10, 10, 15, 0) },
    { cardNumber: 8100999, time: new Date(2026, 8, 10, 10, 17, 30) },
  ]);

  const station = new SIStation(sim, { retries: 0, timeout: 1000 });
  await station.connect();

  const progress = [];
  const punches = await station.readBackup({
    onProgress: (done, total) => progress.push([done, total]),
    now,
  });

  assert.equal(punches.length, 2);
  assert.equal(punches[0].cardNumber, 1234567);
  assert.equal(punches[0].time.getHours(), 10);
  assert.equal(punches[0].time.getMinutes(), 15);
  assert.equal(punches[1].cardNumber, 8100999);
  assert.ok(progress.length >= 1);

  const csv = backupToCsv(punches, { code: 45, mode: 'Control', readTime: now });
  assert.equal(csv.trim().split('\r\n').length, 3);

  await station.disconnect();
});

test('end to end: autosend punches arrive as events and gaps are recovered', async () => {
  const sim = new SimulatedTransport({ code: 32, mode: MODE.CONTROL, latency: 0 });
  const station = new SIControl(sim, { retries: 0, timeout: 1000 });
  await station.connect();
  station.assertAutosendMode();

  const seen = [];
  station.addEventListener('punch', (e) => seen.push(e.detail));

  const t0 = new Date(2026, 8, 10, 10, 0, 0);
  sim.sendPunch(1234567, t0);
  await wait(5);

  // A punch that the station recorded but we never saw on the wire.
  const missed = new Date(2026, 8, 10, 10, 1, 0);
  sim.backup = concatBytes(sim.backup, backupRecordFor(2345678, missed));
  sim.sendPunch(8100999, new Date(2026, 8, 10, 10, 2, 0));
  await wait(30);

  assert.deepEqual(seen.map((p) => p.cardNumber), [1234567, 2345678, 8100999]);
  assert.equal(seen[1].recovered, true);
  assert.equal(seen[2].recovered, false);

  await station.disconnect();
});

test('a command that gets no answer times out rather than hanging', async () => {
  const sim = new SimulatedTransport({ latency: 0 });
  const station = new SIStation(sim, { retries: 0, timeout: 50 });
  await station.connect();

  sim.send = () => {}; // the station stops answering
  await assert.rejects(() => station.beep(1), /No reply/);

  await station.disconnect();
});

test('commands queue instead of interleaving on the wire', async () => {
  const sim = new SimulatedTransport({ latency: 1 });
  const station = new SIStation(sim, { retries: 0, timeout: 1000 });
  await station.connect();

  const order = [];
  await Promise.all([
    station.beep(1).then(() => order.push('a')),
    station.beep(2).then(() => order.push('b')),
    station.getTime().then(() => order.push('c')),
  ]);
  assert.deepEqual(order, ['a', 'b', 'c']);

  await station.disconnect();
});

// helpers used by the autosend test
function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function concatBytes(a, b) {
  const out = new Uint8Array(a.length + b.length);
  out.set(a);
  out.set(b, a.length);
  return out;
}

function backupRecordFor(cardNumber, time) {
  const record = new Uint8Array(8);
  record.set(toBytes(cardNumber, 3), 0);
  record[3] = ((time.getFullYear() - 2000) << 2) | ((time.getMonth() + 1) >> 2);
  record[4] =
    (((time.getMonth() + 1) & 0x3) << 6) |
    (time.getDate() << 1) |
    (time.getHours() >= 12 ? 1 : 0);
  record.set(toBytes((time.getHours() % 12) * 3600 + time.getMinutes() * 60, 2), 5);
  return record;
}
